### PR TITLE
fix: added bucket error handling for 401 status (issue #425)

### LINKED ISSUE #425: When opening overlay when you not logged in you will see error that bucket not found
We shouldn't request bucket if user not logged in, because only user has it
Actual:
image
Expected:
image

### PR DESCRIPTION
**Pull request by denys-kolomiitsev**
- Issue #425

### CODE REVIEW

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Deployment status: success

**Review by IlyaBondar — CHANGES_REQUESTED** [review]
According to the issue "We shouldn't request bucket if user not logged in"

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Deployment status: success

File: src/pages/index.tsx [hunk 1]
```diff
@@ -60,6 +60,10 @@ export default function Home({ initialState }: Props) {
     SettingsSelectors.selectEnabledFeatures,
   );
 
+  const isLoggedin =
+    authDisabled &&
+    (session.status !== 'authenticated' || !isClientSessionValid(session));
```
Comment (IlyaBondar) [inline src/pages/index.tsx]: incorrect name of variable - we check `shouldLogin` here(see on previous line 118)
```suggestion
  const shouldLogin =
    !authDisabled &&
    (session.status !== 'authenticated' || !isClientSessionValid(session));
```

File: src/store/settings/settings.epic.ts [hunk 2]
```diff
@@ -16,19 +16,19 @@ import { SettingsActions, SettingsSelectors } from './settings.reducers';
...
-    switchMap(() =>
+    switchMap(({ payload }) =>
       concat(
         of(ModelsActions.init()),
         of(AddonsActions.init()),
         of(ConversationsActions.init()),
         of(PromptsActions.init()),
         of(UIActions.init()),
-        of(FilesActions.init()),
+        payload.isLoggedin ? of(FilesActions.init()) : EMPTY,
```
Comment (IlyaBondar) [inline src/store/settings/settings.epic.ts]:
```suggestion
        payload.shouldLogin ? EMPTY : of(FilesActions.init()),
```
and we can apply the same for `ModelsActions.init()` and `AddonsActions.init()` to avoid additional requests

**Review by IlyaBondar — CHANGES_REQUESTED** [review]

File: src/pages/index.tsx (hunk 1 above)
Comment (denys-kolomiitsev) [reply src/pages/index.tsx]: Changed.
Thank you!

File: src/store/settings/settings.epic.ts (hunk 2 above)
Comment (denys-kolomiitsev) [reply src/store/settings/settings.epic.ts]: Suggested changes applied.
ModelsActions.init() and AddonsActions.init() added to do request conditionaly

**Review by IlyaBondar — DISMISSED** [review]

**Comment by IlyaBondar** [comment]
/deploy-review
>Deployment status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review

>Deployment status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review

>Deployment status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review

>Deployment status: success

**Review by IlyaBondar — APPROVED** [review]
